//===================================================================================================================
//This part of code is an autogenerated logger code from asp.net core framework======================================
//===================================================================================================================
//===================================================================================================================

using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ShepherdPOS.Api.Models;

namespace ShepherdPOS.Api.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

